name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Setup Solr
        run: |
          docker run -d -p 8983:8983 --name solr solr:8.8 solr -c -f
          docker exec solr bash -c 'sleep 5; wait-for-solr.sh --max-attempts 10 --wait-seconds 5'

      - name: Tests
        run: go test -tags integration -coverprofile=profile.cov
        
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
